#!/usr/bin/env python3
"""Self-aware audit of the exogenous recurrent-local coordinate.

This audit separates three claims:
  1) the numeric scale of z is irrelevant because metric matching uses rank(z);
  2) recurrence is generated by the contact kernel itself;
  3) changing the coordinate realization changes which agents occupy local
     neighbourhoods and may therefore change the M outcome.

The third result is intentionally NOT converted into a binary scientific PASS.
A clean run is reported as AUDIT_COMPLETE, with SENSITIVITY_DETECTED when the
M D-to-Y contrast varies across coordinate realizations. That is a finding,
not a software failure.
"""
import argparse, json, math, re, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BIN = ROOT / 'bin' / 'symmetric_network_matrix'
LINE = re.compile(r'^(R-D|R-Y|M-D|M-Y)\s+rA=([0-9eE+.-]+)\s+rV=([0-9eE+.-]+)\s+rate=([0-9eE+.-]+)\s+pair_x_post=([0-9eE+.-]+)\s+pair_q_post=([0-9eE+.-]+)\s+mutual_pre=([0-9eE+.-]+)\s+repeat1=([0-9eE+.-]+)$')

FIELDS = ['rA','rV','rate','pair_x_post','pair_q_post','mutual_pre','repeat1']

def run(args, offset):
    cmd = [str(BIN), 'matrix', str(args.seeds), str(args.threads),
           str(args.families), str(args.steps), str(args.n), '1.0',
           str(args.shock), str(args.window), str(offset)]
    p = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if p.returncode:
        print(p.stdout, end=''); print(p.stderr, end='')
        raise SystemExit(p.returncode)
    out = {}
    for line in p.stdout.splitlines():
        m = LINE.match(line.strip())
        if m:
            out[m.group(1)] = dict(zip(FIELDS, map(float, m.groups()[1:])))
    if len(out) != 4:
        print(p.stdout)
        raise SystemExit('COORDINATE AUDIT PARSE FAIL')
    return out

def spread(values):
    return max(values) - min(values)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seeds', type=int, default=4)
    ap.add_argument('--threads', type=int, default=4)
    ap.add_argument('--families', type=int, default=1000)
    ap.add_argument('--steps', type=int, default=12000)
    ap.add_argument('--n', type=int, default=4000)
    ap.add_argument('--shock', type=float, default=500.0)
    ap.add_argument('--window', type=float, default=0.06)
    ap.add_argument('--offsets', type=int, nargs='+', default=[0,1,2,3])
    args = ap.parse_args()
    if len(args.offsets) < 2:
        raise SystemExit('At least two coordinate realizations are required')

    runs = {o: run(args, o) for o in args.offsets}
    baseline = runs[args.offsets[0]]

    # Only z is offset. Random-contact cells therefore must be identical.
    for o in args.offsets[1:]:
        for cell in ('R-D','R-Y'):
            for metric in FIELDS:
                if runs[o][cell][metric] != baseline[cell][metric]:
                    raise SystemExit(
                        f'RANDOM_CELL_CHANGED_UNEXPECTEDLY offset={o} cell={cell} metric={metric}'
                    )

    rows = []
    for o, v in runs.items():
        rows.append({
            'offset': o,
            'M_DY_minus_D_rA': v['M-Y']['rA'] - v['M-D']['rA'],
            'M_DY_minus_D_rV': v['M-Y']['rV'] - v['M-D']['rV'],
            'M_repeat1': v['M-Y']['repeat1'],
            'M_repeat5_or20_not_recomputed_here': None,
        })
        if not (0.45 < v['M-Y']['repeat1'] < 0.55):
            raise SystemExit(f'METRIC_RECURRENCE_RANGE_FAIL offset={o}')

    ra = [r['M_DY_minus_D_rA'] for r in rows]
    rv = [r['M_DY_minus_D_rV'] for r in rows]
    ra_spread = spread(ra)
    rv_spread = spread(rv)
    status = 'SENSITIVITY_DETECTED' if (ra_spread > 1e-3 or rv_spread > 1e-3) else 'NO_MATERIAL_SENSITIVITY_AT_THIS_RESOLUTION'

    report = {
        'configuration': vars(args),
        'random_contact_invariant_across_offsets': True,
        'metric_recurrence_preserved_across_offsets': True,
        'M_contrast_rA_spread': ra_spread,
        'M_contrast_rV_spread': rv_spread,
        'status': status,
        'interpretation': (
            'Changing only the exogenous coordinate realization preserves the random cells and '
            'the strong recurrent-contact regime, but changes the metric-local D-to-Y contrast. '
            'Therefore the effect is not proven to be a function of recurrence alone; local-neighbour '
            'realization is a live sensitivity dimension.' if status == 'SENSITIVITY_DETECTED' else
            'No material M contrast sensitivity was detected at the tested resolution; this does not '
            'establish general coordinate-invariance.'
        ),
        'runs': runs,
        'metric_contrasts': rows,
    }
    out = ROOT / 'verification' / 'coordinate_realization_audit.json'
    out.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    print(f'COORDINATE REALIZATION AUDIT COMPLETE status={status}')
    print(f'Offsets: {args.offsets}')
    print(f'M_DY-D rA spread={ra_spread:.6f} rV spread={rv_spread:.6f}')
    for row in rows:
        print(f"offset={row['offset']} M_DY-D rA={row['M_DY_minus_D_rA']:.6f} rV={row['M_DY_minus_D_rV']:.6f} repeat1={row['M_repeat1']:.6f}")
    print(f'JSON: {out}')

if __name__ == '__main__':
    main()
